Repository LondonKPC/lkpc-frontend, pull requests merged in 2024-12, with the labels that each got.

#9 Very Very basic layout
  app/globals.css
  app/home/page.tsx
  app/page.tsx
  components/Footer.tsx
  images/capy.png
  package-lock.json
  package.json
Labels: enhancement

#27 Created github workflow template to deploy to S3
  .github/scripts/deployFrontend.sh
  .github/workflows/deployToS3.yaml
  next.config.ts
Labels: enhancement

#47 re-added footer
  components/Footer.tsx
  images/discord.png
  images/email.png
  images/insta.png
Labels: enhancement

#52 Refactored file structure + navbar
  app/home/page.tsx
  app/layout.tsx
  components/footer/Footer.tsx
  components/navbar/NavBar.css
  components/navbar/NavBar.tsx
  public/LKPC_Logo.png
  public/discord.png
  public/email.png
  public/file.svg
  public/globe.svg
  public/insta.png
  public/next.svg
  public/vercel.svg
  public/window.svg
Labels: enhancement

#37 Web design proposal
  README.md
Labels: documentation

#57 Fixed white bar at smaller widths
  app/home/page.tsx
  components/footer/Footer.tsx
  components/navbar/NavBar.tsx
  images/capy.png
Labels: bug

#59 Refactor NavBar
  .github/workflows/deploy_frontend_dev.yaml
  .github/workflows/deploy_frontend_prod.yaml
  app/home/page.tsx
  app/layout.tsx
  components/footer/Footer.tsx
  components/navbar/NavBar.css
  components/navbar/NavBar.tsx
  components/sidebar/SideBar.css
  components/sidebar/SideBar.tsx
  constants/routeDefinitions.ts
  hooks/useClickOutside.ts
  images/LKPC_Logo.svg
  images/bars.svg
  images/calendar.svg
  images/calendar_white.svg
  images/discord.svg
  images/email.svg
  images/handshake.svg
  images/handshake_white.svg
  images/instagram.svg
  images/location.svg
  images/login.svg
  images/login_white.svg
  images/message.svg
  images/message_white.svg
  images/news.svg
  images/pen.svg
  images/telephone.svg
  images/user.svg
  images/xmark.svg
  images/xmark_white.svg
  public/LKPC_Logo.png
  public/discord.png
  public/email.png
  public/insta.png
Labels: enhancement

#63 Footer icons and horizontal scrollbar fix
  app/layout.tsx
  components/footer/Footer.tsx
  components/navbar/NavBar.tsx
Labels: documentation
